// This file is auto-generated by: npm run db:types
// Run `npm run db:types` after any schema migration to regenerate.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export interface Database {
  public: {
    Tables: {
      organisations: {
        Row: {
          id: string
          name: string
          slug: string
          theme_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          theme_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          theme_id?: string | null
          created_at?: string
        }
      }
      courses: {
        Row: {
          id: string
          org_id: string
          title: string
          description: string | null
          cover_image_url: string | null
          theme_id: string | null
          status: 'draft' | 'published' | 'archived'
          scorm_version: string
          metadata: Json
          created_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          org_id: string
          title: string
          description?: string | null
          cover_image_url?: string | null
          theme_id?: string | null
          status?: 'draft' | 'published' | 'archived'
          scorm_version?: string
          metadata?: Json
          created_by?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          org_id?: string
          title?: string
          description?: string | null
          cover_image_url?: string | null
          theme_id?: string | null
          status?: 'draft' | 'published' | 'archived'
          scorm_version?: string
          metadata?: Json
          created_by?: string | null
          updated_at?: string
          deleted_at?: string | null
        }
      }
      lessons: {
        Row: {
          id: string
          course_id: string
          title: string
          position: number
          is_section_header: boolean
          created_at: string
        }
        Insert: {
          id?: string
          course_id: string
          title: string
          position: number
          is_section_header?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          course_id?: string
          title?: string
          position?: number
          is_section_header?: boolean
        }
      }
      blocks: {
        Row: {
          id: string
          lesson_id: string
          type: string
          position: number
          content: Json
          settings: Json
          created_at: string
        }
        Insert: {
          id?: string
          lesson_id: string
          type: string
          position: number
          content?: Json
          settings?: Json
          created_at?: string
        }
        Update: {
          id?: string
          lesson_id?: string
          type?: string
          position?: number
          content?: Json
          settings?: Json
        }
      }
      themes: {
        Row: {
          id: string
          org_id: string | null
          name: string
          primary_color: string | null
          secondary_color: string | null
          accent_color: string | null
          background_color: string | null
          text_color: string | null
          heading_font: string | null
          body_font: string | null
          button_style: Json | null
          logo_url: string | null
          cover_style: 'gradient' | 'image' | 'solid' | 'video' | null
          custom_css: string | null
          created_at: string
        }
        Insert: {
          id?: string
          org_id?: string | null
          name: string
          primary_color?: string | null
          secondary_color?: string | null
          accent_color?: string | null
          background_color?: string | null
          text_color?: string | null
          heading_font?: string | null
          body_font?: string | null
          button_style?: Json | null
          logo_url?: string | null
          cover_style?: 'gradient' | 'image' | 'solid' | 'video' | null
          custom_css?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string | null
          name?: string
          primary_color?: string | null
          secondary_color?: string | null
          accent_color?: string | null
          background_color?: string | null
          text_color?: string | null
          heading_font?: string | null
          body_font?: string | null
          button_style?: Json | null
          logo_url?: string | null
          cover_style?: 'gradient' | 'image' | 'solid' | 'video' | null
          custom_css?: string | null
        }
      }
      quiz_attempts: {
        Row: {
          id: string
          course_id: string
          learner_id: string
          score_raw: number | null
          score_max: number | null
          score_min: number | null
          lesson_status: string | null
          suspend_data: string | null
          started_at: string | null
          completed_at: string | null
        }
        Insert: {
          id?: string
          course_id: string
          learner_id: string
          score_raw?: number | null
          score_max?: number | null
          score_min?: number | null
          lesson_status?: string | null
          suspend_data?: string | null
          started_at?: string | null
          completed_at?: string | null
        }
        Update: {
          score_raw?: number | null
          score_max?: number | null
          score_min?: number | null
          lesson_status?: string | null
          suspend_data?: string | null
          completed_at?: string | null
        }
      }
      org_users: {
        Row: {
          id: string
          org_id: string
          user_id: string
          role: 'org_admin' | 'author' | 'reviewer' | 'viewer'
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          user_id: string
          role?: 'org_admin' | 'author' | 'reviewer' | 'viewer'
          created_at?: string
        }
        Update: {
          role?: 'org_admin' | 'author' | 'reviewer' | 'viewer'
        }
      }
    }
    Functions: {
      auth_org_id: { Args: Record<never, never>; Returns: string }
      auth_org_role: { Args: Record<never, never>; Returns: string }
    }
  }
}