// This file is auto-generated by: npm run db:types
// Do not edit manually.
// Run `npm run db:types` after any schema migration to regenerate.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export interface Database {
  public: {
    Tables: {
      organisations: {
        Row: {
          id: string
          name: string
          slug: string
          theme_id: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['organisations']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['organisations']['Insert']>
      }
      courses: {
        Row: {
          id: string
          org_id: string
          title: string
          description: string | null
          cover_image_url: string | null
          theme_id: string | null
          status: 'draft' | 'published' | 'archived'
          scorm_version: string
          metadata: Json
          created_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['courses']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['courses']['Insert']>
      }
      lessons: {
        Row: {
          id: string
          course_id: string
          title: string
          position: number
          is_section_header: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['lessons']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['lessons']['Insert']>
      }
      blocks: {
        Row: {
          id: string
          lesson_id: string
          type: string
          position: number
          content: Json
          settings: Json
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['blocks']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['blocks']['Insert']>
      }
      themes: {
        Row: {
          id: string
          org_id: string | null
          name: string
          primary_color: string | null
          secondary_color: string | null
          accent_color: string | null
          background_color: string | null
          text_color: string | null
          heading_font: string | null
          body_font: string | null
          button_style: Json | null
          logo_url: string | null
          cover_style: 'gradient' | 'image' | 'solid' | 'video' | null
          custom_css: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['themes']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['themes']['Insert']>
      }
      quiz_attempts: {
        Row: {
          id: string
          course_id: string
          learner_id: string
          score_raw: number | null
          score_max: number | null
          score_min: number | null
          lesson_status: string | null
          suspend_data: string | null
          started_at: string | null
          completed_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['quiz_attempts']['Row'], 'id'>
        Update: Partial<Database['public']['Tables']['quiz_attempts']['Insert']>
      }
      org_users: {
        Row: {
          id: string
          org_id: string
          user_id: string
          role: 'org_admin' | 'author' | 'reviewer' | 'viewer'
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['org_users']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['org_users']['Insert']>
      }
    }
    Functions: {
      auth_org_id: { Args: Record<never, never>; Returns: string }
      auth_org_role: { Args: Record<never, never>; Returns: string }
    }
  }
}
